### ISSUE TITLE
[Bug]: PyPI package missing requirements.txt

### ISSUE THREAD

**Issue by noUsernamesLef7** [linode/ansible-specdoc#45]
### Expected Behavior

Downloading the package from PyPI should include the requirements.txt file as the included setup.py references this file and crashes without it.

### Actual Behavior

When downloading the latest version (0.0.17) of the package from PyPI, there is no requirements.txt file included. I also checked 0.0.16 and found it missing from that package.

### Steps to Reproduce

1. Download 0.0.17 package from PyPI
2. Extract using method of choice
3. Observe that the requirements.txt file is absent

### Error Output

```
Traceback (most recent call last):
  File "/home/.../src/ansible_specdoc-0.0.17/setup.py", line 31, in <module>
    install_requires=requirements_path.read_text().splitlines(),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/pathlib.py", line 1027, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/pathlib.py", line 1013, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/.../src/ansible_specdoc-0.0.17/requirements.txt'
```

**Comment by AryanK1511** [comment]
I believe I know how to fix this. @noUsernamesLef7, are you able to assign this issue to me?

**Comment by AryanK1511** [comment]
@noUsernamesLef7 Also could ou let me know what command you are running so that I can reproduce the error on my end too. I have a way of seeing that the requirements file does not exist but I am curious about the command that you are using

**Comment by ezilber-akamai** [comment]
Hello. Thank you for reporting this issue! I have created a ticket to fix this and we will tag this issue in the PR.
